/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthTimesIndexImport } from './routes/_auth/times/index'
import { Route as AuthTeamIndexImport } from './routes/_auth/team/index'
import { Route as AuthTimesTimeIdIndexImport } from './routes/_auth/times/$timeId/index'
import { Route as AuthTimesTimeIdEditImport } from './routes/_auth/times/$timeId/edit'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTimesIndexRoute = AuthTimesIndexImport.update({
  path: '/times/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTeamIndexRoute = AuthTeamIndexImport.update({
  path: '/team/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTimesTimeIdIndexRoute = AuthTimesTimeIdIndexImport.update({
  path: '/times/$timeId/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTimesTimeIdEditRoute = AuthTimesTimeIdEditImport.update({
  path: '/times/$timeId/edit',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/team/': {
      id: '/_auth/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthTeamIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/times/': {
      id: '/_auth/times/'
      path: '/times'
      fullPath: '/times'
      preLoaderRoute: typeof AuthTimesIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/times/$timeId/edit': {
      id: '/_auth/times/$timeId/edit'
      path: '/times/$timeId/edit'
      fullPath: '/times/$timeId/edit'
      preLoaderRoute: typeof AuthTimesTimeIdEditImport
      parentRoute: typeof AuthImport
    }
    '/_auth/times/$timeId/': {
      id: '/_auth/times/$timeId/'
      path: '/times/$timeId'
      fullPath: '/times/$timeId'
      preLoaderRoute: typeof AuthTimesTimeIdIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthTeamIndexRoute: typeof AuthTeamIndexRoute
  AuthTimesIndexRoute: typeof AuthTimesIndexRoute
  AuthTimesTimeIdEditRoute: typeof AuthTimesTimeIdEditRoute
  AuthTimesTimeIdIndexRoute: typeof AuthTimesTimeIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthTeamIndexRoute: AuthTeamIndexRoute,
  AuthTimesIndexRoute: AuthTimesIndexRoute,
  AuthTimesTimeIdEditRoute: AuthTimesTimeIdEditRoute,
  AuthTimesTimeIdIndexRoute: AuthTimesTimeIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/': typeof AuthIndexRoute
  '/team': typeof AuthTeamIndexRoute
  '/times': typeof AuthTimesIndexRoute
  '/times/$timeId/edit': typeof AuthTimesTimeIdEditRoute
  '/times/$timeId': typeof AuthTimesTimeIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/team': typeof AuthTeamIndexRoute
  '/times': typeof AuthTimesIndexRoute
  '/times/$timeId/edit': typeof AuthTimesTimeIdEditRoute
  '/times/$timeId': typeof AuthTimesTimeIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/team/': typeof AuthTeamIndexRoute
  '/_auth/times/': typeof AuthTimesIndexRoute
  '/_auth/times/$timeId/edit': typeof AuthTimesTimeIdEditRoute
  '/_auth/times/$timeId/': typeof AuthTimesTimeIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/team'
    | '/times'
    | '/times/$timeId/edit'
    | '/times/$timeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/team' | '/times' | '/times/$timeId/edit' | '/times/$timeId'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/'
    | '/_auth/team/'
    | '/_auth/times/'
    | '/_auth/times/$timeId/edit'
    | '/_auth/times/$timeId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/team/",
        "/_auth/times/",
        "/_auth/times/$timeId/edit",
        "/_auth/times/$timeId/"
      ]
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/team/": {
      "filePath": "_auth/team/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/times/": {
      "filePath": "_auth/times/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/times/$timeId/edit": {
      "filePath": "_auth/times/$timeId/edit.tsx",
      "parent": "/_auth"
    },
    "/_auth/times/$timeId/": {
      "filePath": "_auth/times/$timeId/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
