/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TimesIndexImport } from './routes/times/index'
import { Route as TeamIndexImport } from './routes/team/index'
import { Route as TimesTimeIdImport } from './routes/times/$timeId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TimesIndexRoute = TimesIndexImport.update({
  path: '/times/',
  getParentRoute: () => rootRoute,
} as any)

const TeamIndexRoute = TeamIndexImport.update({
  path: '/team/',
  getParentRoute: () => rootRoute,
} as any)

const TimesTimeIdRoute = TimesTimeIdImport.update({
  path: '/times/$timeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/times/$timeId': {
      id: '/times/$timeId'
      path: '/times/$timeId'
      fullPath: '/times/$timeId'
      preLoaderRoute: typeof TimesTimeIdImport
      parentRoute: typeof rootRoute
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamIndexImport
      parentRoute: typeof rootRoute
    }
    '/times/': {
      id: '/times/'
      path: '/times'
      fullPath: '/times'
      preLoaderRoute: typeof TimesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/times/$timeId': typeof TimesTimeIdRoute
  '/team': typeof TeamIndexRoute
  '/times': typeof TimesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/times/$timeId': typeof TimesTimeIdRoute
  '/team': typeof TeamIndexRoute
  '/times': typeof TimesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/times/$timeId': typeof TimesTimeIdRoute
  '/team/': typeof TeamIndexRoute
  '/times/': typeof TimesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/times/$timeId' | '/team' | '/times'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/times/$timeId' | '/team' | '/times'
  id: '__root__' | '/' | '/times/$timeId' | '/team/' | '/times/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimesTimeIdRoute: typeof TimesTimeIdRoute
  TeamIndexRoute: typeof TeamIndexRoute
  TimesIndexRoute: typeof TimesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimesTimeIdRoute: TimesTimeIdRoute,
  TeamIndexRoute: TeamIndexRoute,
  TimesIndexRoute: TimesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/times/$timeId",
        "/team/",
        "/times/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/times/$timeId": {
      "filePath": "times/$timeId.tsx"
    },
    "/team/": {
      "filePath": "team/index.tsx"
    },
    "/times/": {
      "filePath": "times/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
